# Generated by Django 3.0.3 on 2022-06-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_coordinate', models.IntegerField()),
                ('end_coordinate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('domain_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=32760)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.IntegerField()),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinTaxonomyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism.Protein')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism.Domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='organism.ProteinDomainLink', to='organism.Domain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ManyToManyField(through='organism.ProteinTaxonomyLink', to='organism.Taxonomy'),
        ),
        migrations.AddField(
            model_name='domain',
            name='pfam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism.Pfam'),
        ),
    ]
